name: Build GraalVM Executable and Push To Railway

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'

      - name: Build with Maven
        run: mvn -Pnative native:compile -DskipTests

      - name: Move Executable
        run: mv ./target/appBuild ./
      
      - name: Install Railway CLI
        run: npm i -g @railway/cli
      
      - name: Verify Railway CLI installation
        run: railway --version

      - name: Deploy to Railway
        run: railway up --service=${{ secrets.SVC_ID }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          SVC_ID: ${{ secrets.SVC_ID }}